### ISSUE TITLE
Oops: decoding an arraybuffer vs uint8array

### ISSUE THREAD

**Issue by getify** [oslo-project/cbor#4]
I am comparing this library [to another CBOR decoder](https://github.com/paroga/cbor-js/blob/master/cbor.js) -- evaluating if I can replace *that* one with your library, as a dependency in my tool -- and I ran into a bit of a footgun.

Your `decodeCBOR()` / `decodeCBORIntoNative()` functions expect a `Uint8Array` value. However, I passed a raw `ArrayBuffer`, because that's what comes back in the `attestationObject` property of the result of webauthn `create()`. And it "failed", but not with an exception, it just returned `[0, 1]`.

----

NOTE: I was passing in the raw value because that other CBOR library internally uses `DataView` for its parsing, which means it's forgiving of receiving a raw buffer instead of the typed array.

----

I lost about 20 minutes to this mistake, before figuring out what I was doing wrong. It would probably have been helpful if your functions threw an exception if not being provided what's expected, would have saved me from that confusion.

Alternatively, perhaps you could relax (for convenience sake) your acceptance, to include raw `ArrayBuffer` values -- again, since that's what the webauthn API returns, so a lot of users will probably trip over this -- and detect if that's been passed, and just automatically cast to a `Uint8Array`?

Or lastly, it might be helpful minimally, if in your documentation you call out this little gotcha and at least remind users (like me!) that they need to make sure to pass `new Uint8Array( theValue )` into your functions?

**Comment by pilcrowOnPaper** [comment]
This should be caught by TypeScript, no?

**Comment by getify** [comment]
That's probably true. However I don't use TypeScript, so it wasn't helpful to me in this case.

**Comment by An39gmail** [comment]
Projetos de inclusão social. Onde pessoas importam e não são invisíveis. Empregados ou não. Dentro ou fora das suas comunidades. Fato é.  São irrevantes se as questões sociais delas se resolvem. No final reina o capital Neoliberal.
